### ISSUE TITLE
Use 410 Gone for deleted documents

### ISSUE THREAD

**Issue by kjetilk** [solid/specification#103]
It just occurred to me that if we retain server-controlled metadata #65 , then it would be trivial to return `410 Gone` for resources that have been deleted.

**Comment by csarven** [comment]
https://github.com/solid/specification/issues/14
https://github.com/solid/specification/issues/72

**Comment by timbl** [comment]
I would strongly argue against this, as it increases the distance between a unix file system and a solid one.   I do not want my server to have to track things people have deleted. 

It is also a potential privacy problem, in that a  user can currently expect that filename (which can of course  be embarrassing) is gone when they delete the file itself.

 I propose dropping this suggestion.

**Comment by csarven** [comment]
Based on my review of the issues listed in https://github.com/solid/specification/issues/103#issuecomment-547366334 and the current direction of the spec, servers are not required to return 410 for deleted resources. 410 is currently only mentioned for some cases in non-normative language.

Unless there is a reason to prohibit servers from ever returning a 410, which is I think a stronger position than what @timbl outlined, I agree to drop the suggestion.
