### ISSUE TITLE
This repo - 'default' vs 'master' branches?

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/specification#110]
Operational question - currently, on this repo, we have `master` as the default branch, but serve the spec off of the `gh-pages` branch.

Is that intentional? If yes, do we have a process of how which branch to make PRs to?
Better yet, can we just merge the two, and serve github.io off of the `master` branch?

**Comment by RubenVerborgh** [comment]
`gh-pages` is a compiled version generated by Travis; PRs should go to `master`.

The reason they are different branches is because the source code goes into `master`, and the compiled version into `gh-pages`.

**Comment by dmitrizagidulin** [comment]
Thanks!
