### ISSUE TITLE
WebSockets and HTTP/2

### ISSUE THREAD

**Issue by kjetilk** [solid/specification#122]
I think we need to review our use of Websockets. 

Now, Websockets are supported in a [standalone package](https://github.com/solid/node-solid-ws), which has not received much attention. The use cases that motivates Websocket, could to a great extent be done using [HTTP/2 and SSE](https://www.infoq.com/articles/websocket-and-http2-coexist), even though HTTP/2 doesn't entirely replace Websockets.

We should discuss whether we should bring such use cases under the HTTP umbrella, support HTTP/2 for Solid and integrate SSE into the platform.

**Comment by justinwb** [comment]
Wanted to record that there was a live discussion where @timbl asked that we evaluate the use of HTTP/2 + SSE moving forward (to ultimately replace websockets), with the caveat we need a documented candidate proposal with accompanying implementation, so that the approach can be properly evaluated and vetted.

**Comment by kjetilk** [comment]
There appears to have been more discussions on this that haven't been recorded here, so I'm moving it back to Under Discussion.

**Comment by elf-pavlik** [comment]
https://github.com/whatwg/html/issues/2177#issuecomment-332071504

> I work on the team that maintains EventSource for Chrome. EventSource is not being actively developed. We feel resources are better spent in filling the gaps in the more generally-useful facilities provided by fetch().

> To give some idea of scale, fetch() body streaming is already used on ten times as many pages as EventSource in Chrome.

Let's take a look at `fetch()` body streaming. This would also remove limitations of `Content-Type: text/event-stream`

**Comment by elf-pavlik** [comment]
I've made simple demo of streaming fetch response: https://elf-pavlik-live-fetch.glitch.me/

If you open console in dev tools you can see each timestamp sent from the server logging to the console. On the client side it boiled down to few simple lines:

```js
     (async function () {
        const foo = await fetch('https://elf-pavlik-live-fetch.glitch.me/stream')
        const reader = foo.body.getReader()
        const decoder = new TextDecoder()
        reader.read().then(function handle({done, value}) {
            console.log(decoder.decode(value))
            return reader.read().then(handle)
        })
      })()
```

@michielbdejong I recall you working recently on implementing Websockets based subscriptions. Do you think simple streaming `fetch` like above would offer comparable feature?

**Comment by michielbdejong** [comment]
Yes, smart!

**Comment by elf-pavlik** [comment]
We discussed it shortly today during Authentication Panel meeting and it looks that new solid-auth-fetcher should 'just work' since it uses native `fetch` interface. @jaxoncreed

**Comment by elf-pavlik** [comment]
> we need a documented candidate proposal with accompanying implementation, so that the approach can be properly evaluated and vetted.

@michielbdejong what would it take to add prototype implementation to inrupt / wac-ldp ? I believe the whole access control part would also 'just work' and we would only need to define how to format that streaming response.

**Comment by acoburn** [comment]
A streaming fetch implies a one-way communication channel (server -> client). @elf-pavlik what is your proposal for how a client would subscribe to multiple resources? Would a specialized endpoint exist for every resource? How would a server distinguish between a regular GET and a streaming fetch like this?

**Comment by elf-pavlik** [comment]
> what is your proposal for how a client would subscribe to multiple resources?

Client could use `POST` instead of `GET` and include details for the subscription in the body.

> Would a specialized endpoint exist for every resource?

I don't think we need that, if we use `POST` for initial subscription, it could return `201` with `Location` which could get used for the same subscription.

> How would a server distinguish between a regular GET and a streaming fetch like this?

I think we would have distinct IRIs for regular LDPResources and those streaming resources. Server would only need to support one kind of response for given IRI.

**Comment by acoburn** [comment]
@elf-pavlik I am not opposed to this suggestion, but this is a pretty significant departure design-wise from the current WebSocket interface. 

@RubenVerborgh has mentioned numerous times that what the realtime notification feature really needs is a proper design (whether it uses WebSockets or something else). It would be easier to evaluate this suggestion if you were in a position to offer a more complete design document with both server and client interactions.

**Comment by elf-pavlik** [comment]
@acoburn I think we should document use cases and based on them requirements for 'subscribing to updates' feature. Few questions I hope it would help answering:

* how does it relate to data discovery? (interoperability panel) - possibly client would simply want to receive updates on changes to anything it can access.
* how it suppose to differ from cases relying on [Push API](https://www.w3.org/TR/push-api/) - for example: user interactively controls what they want to receive via Push API, but clients uses 'subscribing to updates' in background without any user involvement.

**Comment by michielbdejong** [comment]
See also https://github.com/solid/specification/issues/52#issuecomment-682491952

**Comment by kjetilk** [comment]
With the resolution of #50 , it is clear that it isn't WebSockets vs SSE as it is framed in this issue. I therefore think it is appropriate to close this issue, but others are of course welcome to discuss other alternative protocols to WebSockets.
