### ISSUE TITLE
server-side author annotation

### ISSUE THREAD

**Issue by michielbdejong** [solid/specification#127]
An idea that @RubenVerborgh mentioned yesterday, which I think sounds brilliant:

When a client writes to a server, for instance a PATCH that adds triples to a doc or a POST to an inbox, we could have a specific predicate (e.g. http://xmlns.com/foaf/spec/#term_maker) that triggers a server-side check: If you add the triple
```turtle
<> foaf:maker <https://michielbdejong.inrupt.net/profile/card#me>.
```
in an unauthenticated request, or when authenticated as anyone other than `https://michielbdejong.inrupt.net/profile/card#me`, the request would fail with a meaningful error message.

When then doing a GET for such a document, there should probably be a response header that allows the server to state that "this RDF source contains `foaf:maker` triples that have all been checked by this server at write time"

**Comment by csarven** [comment]
I think the underlying issue is covered in https://github.com/solid/specification/issues/66 . If this is intended as a proposed solution, I suggest to move it there.

**Comment by michielbdejong** [comment]
Continued in #66
