### ISSUE TITLE
Determine the URIs for the specifications

### ISSUE THREAD

**Issue by csarven** [solid/specification#141]
We need to have some commitment for the spec URIs. At the moment, we are using GitHub pages as an interim solution, however long term commitment and URI persistence is important for the project. We could transition different specs at different times as the project and documents evolve.

Basic things to consider:

* Under whose authority?
* What URI space? (under w3.org; community, wiki, member submission, or solidproject.org, github.io, w3id.org, ..)

This issue should be addressed by the Solid process and the W3C Solid Community Group.

**Comment by justinwb** [comment]
Agree 👍- we need to decide on this and formalize that decision in our governance process.

**Comment by kjetilk** [comment]
My proposal would be to publish them on solidproject.org.

**Comment by timbl** [comment]
Agree.   Suggest `solidproject.org/specs`

**Comment by Mitzi-Laszlo** [comment]
Something for the solidproject.org website kanban board to arrange

**Comment by csarven** [comment]
Consensus was reached in https://github.com/solid/specification/blob/main/meetings/2020-11-30.md to publish specs using URI Template: `https://solidproject.org/TR/{id}`.

https://github.com/solid/solidproject.org/issues/249 documents the URI Template for Solid Technical Reports, including persistent and non-persistent URIs.

https://github.com/solid/solidproject.org/pull/489 introduced the Solid Project Terms including the URI Persistence Policy section for persistent Solid Technica Reports.
