### ISSUE TITLE
WebID-TLS specification

### ISSUE THREAD

**Issue by namedgraph** [solid/specification#148]
Hi,

why is a W3C document being hijacked by Solid?

**WebID-TLS** specification is this: https://dvcs.w3.org/hg/WebID/raw-file/tip/spec/tls-respec.html

What is https://solid.github.io/specification/webid-tls/ supposed to be and why is referred to as WebID-TLS?

**Comment by elf-pavlik** [comment]
In #140 I proposed removing it from this repository

**Comment by kjetilk** [comment]
Not sure. I'm not even sure it is intentional, but also note that it is just a 6 y.o. Editor's draft of a CG, it holds no official position, and may be superseded by other documents, so I can't see how that's a major incursion.

**Comment by csarven** [comment]
Closing as per #140 and the updates that followed.
