### ISSUE TITLE
Using 'Pod' consistently throughout all documentation?

### ISSUE THREAD

**Issue by pmcb55** [solid/specification#15]
Just to make sure we have this tracked - #12 (and I'm sure other places too!) uses the term 'data pod' consistently, yet the agreed terminology (within inrupt at least) was to use the term 'Pod' everywhere. Personally, I think the word 'data' in 'data pod' is redundant anyway, so my suggestion is to replace all references of 'data pod' with 'Pod.

**Comment by RubenVerborgh** [comment]
Related: #16 (for the actual content of the definitions).

**Comment by RubenVerborgh** [comment]
> uses the term 'data pod' consistently, yet the agreed terminology (within inrupt at least) was to use the term 'Pod' everywhere

My take on this is that specifications generally use more precise terminology throughout. "Pod" by itself is not sufficiently meaningful or precise; "data pod" is.

I also think there's a difference between the Pod of inrupt materials, versus the wording in technical specifications (which would not capitalize an ordinary noun).

No very strong opinion though.

**Comment by csarven** [comment]
Opinion:

I would suggest to omit the term "pod" from specs until there is an actual definition (with some consensus) about its features, capabilities, or outlining a system with minimal aspects that would classify as one. 

What does a system need to be a "pod" or what would disqualify one? The definition for the most part may just end up being self-referential to the spec(s).

It is useful to start with existing definitions like for example, store/storage/dataspace/data service/identity provider/access controlled stuff... and see how much they differ from a "pod". If it going to ballpark convey "an access-controlled Linked Dataspace .." just say that without introducing a new term into the specs.

**Comment by kjetilk** [comment]
> Opinion:
> 
> I would suggest to omit the term "pod" from specs until there is an actual definition (with some consensus) about its features, capabilities, or outlining a system with minimal aspects that would classify as one.

I'm almost :+1:  on that, but I think we need to have that term, and we need to define at ASAP.

**Comment by RubenVerborgh** [comment]
Let us further refine in #16, as suggested by @csarven.
