### ISSUE TITLE
Valid serializations of ACL resources

### ISSUE THREAD

**Issue by kjetilk** [solid/specification#150]
This PR https://github.com/solid/node-solid-server/pull/1407 assumes that Turtle is the only valid content-type for ACL resources. While we could probably live with that for now, it seems overly restrictive, other RDF serializations should be equally permitted, I think.

**Comment by csarven** [comment]
Agreed. As already agreed, ACL resources are RDF Sources and so will follow the recommendation from #45

**Comment by bourgeoa** [comment]
This PR solid/node-solid-server#1407 was made in line with the actual resource-mapper.js
> L28     overrideTypes = { acl: 'text/turtle', meta: 'text/turtle' }

with no other intention, and hope it could be approved in NSS 5.x context.

**Comment by RubenVerborgh** [comment]
This is just on disk. It means: if you see a .acl extension on disk, the thing is Turtle. You can still conneg.
