### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by michielbdejong** [solid/specification#164]
It's possible to get notified about updates via websockets-pubsub, but sometimes the mean time between updates is so long (e.g. months) that this is unfeasible. Imagine subscribing to alerts that your friends send out when their home address changes. That app would at worst need to subscribe to one websocket per friend (at least one websocket per different pod provider where you have at least one friend), and it would probably not see `pub` events for years on end for some of them.

So it seems more sane to use webhooks. I think LDN allows this. So You send each of your friends some sort of subscribe request where you give your own inbox (or at least some LDN endpoint you read) as the notification endpoint. When they change the address in their pod, the pod server would send out `pub` events to all subscribed websocket clients, but also make outgoing server-to-server http calls to a number of webhooks.

We would need mechanisms to:
* set up a webhook.
* tear down a webhook.
* throttle / deal with DoS considerations.

Currently, some apps already do something like this from the client side: they edit for instance the game state, and also do a client-to-other-pod-server POST, to create a notification in the other player's game inbox. But this proposed spec change is about the idea of doing that server-to-server.

**Comment by csarven** [comment]
Can we partly approach this issue in eg. #49 ? 

The bit about sending server-server notifications given an activity, or resource/graph change would be useful. I think this is in our radar. Also briefly mentioned use cases in https://github.com/solid/notifications-panel/issues/1 about changes, subscribing and unsubscribing.

My straw man thinking is that LDN with notification payload expressing "subscribe" eg. "send notifications to this inbox when a particular resource changes", could work. Server would keep a collection of subscriptions. As you know, there has been some (experimental) work on that already, partly using AS2. Would formalising something like that generally address the case you bring up?

**Comment by michielbdejong** [comment]
superseded by #457
