### ISSUE TITLE
Is WAC-Allow part of the solid spec?

### ISSUE THREAD

**Issue by Otto-AA** [solid/specification#170]
I've seen that the node-solid-server implemented a `WAC-Allow` header for identifying which access is granted for the requested resource. Is this also part of the solid api spec, or just a feature of this specific implementation?

Related issue in NSS: https://github.com/solid/node-solid-server/issues/246

**Comment by RubenVerborgh** [comment]
Let's also have an issue for the problem; as this is just one possible solution. Other solutions include the `Link` header.

**Comment by csarven** [comment]
Transferred https://github.com/solid/specification/issues/171 as the original problem.

**Comment by csarven** [comment]
Proposal/requirements merged via PR https://github.com/solid/specification/pull/210 . See further details/discussion on concerns of this header, as well as use cases for different permission groups. Implementation feedback is always useful/welcome. Please follow up with new issues/proposals.
