### ISSUE TITLE
Link relation URIs for Auxiliary Resource types

### ISSUE THREAD

**Issue by justinwb** [solid/specification#172]
As defined in https://github.com/solid/specification/pull/156, Auxiliary Resources of various types are associated with Solid resources through link relations, including some that are being newly introduced.

Using rel="acl" and rel="describedby" has been used routinely in solid to date. In the new spec text we encourage the use of the corresponding URIs for both, and only have URIs for new terms. 

Shape validation, Server Managed, and Configuration are new types which do not have defined URIs yet, but are proposed below for agreement.

| Auxiliary Type | Link Relation |
|---------------|--------------|
| Web Access Control | "acl" or http://www.w3.org/ns/solid/terms#acl |
| Resource Description |  "describedby" or https://www.w3.org/ns/iana/link-relations/relation#describedby |
| Shape Validation | http://www.w3.org/ns/solid/terms#shape |
| Server Managed | http://www.w3.org/ns/solid/terms#servermanaged |
| Configuration | http://www.w3.org/ns/solid/terms#configuration |

**Comment by csarven** [comment]
Not sure how to handle this issue. If that's what's proposed through the issues, panels, PRs etc, then that's all there is to it. If there is an additional discussion that's needed, then:

re ACL, this is a duplicate issue of https://github.com/solid/specification/issues/54 ( https://github.com/solid/web-access-control-spec/issues/21 ). A bit more discussion in https://github.com/solid/data-interoperability-panel/issues/37 .

Since SHACL and ShEx are used out there, how are their elations named in the wild? Not only in the Solid universe but anything using SHACL and ShEx. Did we approach the SHACL community to see what they've considered?

I don't see a strong distinction between describedby and configuration - at least the their descriptions are not jumping out at me.

New terms should probably be brought up to https://github.com/solid/vocab at some point.

**Comment by justinwb** [comment]
> Not sure how to handle this issue. If that's what's proposed through the issues, panels, PRs etc, then that's all there is to it.

Yes this is what came through the panel. It was created after @RubenVerborgh [suggested](https://github.com/solid/specification/pull/156/files/4c4dde9fe6352dd5802fd4b4b4d0fc98c7de7657#r396717706) in editorial review that DCAT 2.0 profiles be considered, presumably for http://www.w3.org/ns/solid/terms#shape.

> re ACL, this is a duplicate issue of #54 ( [solid/web-access-control-spec#21](https://github.com/solid/web-access-control-spec/issues/21) ). A bit more discussion in [solid/data-interoperability-panel#37](https://github.com/solid/data-interoperability-panel/issues/37) .

Agree - I think we need to make a definitive decision on this. Lets include this ticket on agenda for next editorial session.

> Since SHACL and ShEx are used out there, how are their relations named in the wild? Not only in the Solid universe but anything using SHACL and ShEx. Did we approach the SHACL community to see what they've considered?

The shape validation section is queued up next, but the intent is that the URI targeted by the http://www.w3.org/ns/solid/terms#shape relation is not the shape itself, but an rdf resource that references it/them along with additional parameters like type, validation level, etc.

> I don't see a strong distinction between describedby and configuration - at least the their descriptions are not jumping out at me.

At a high level, describedby is meant as a place to store any kind of metadata about a given resource, and configuration is meant to store information to influence how the resource is processed and/or handled (such as whether mementos should be maintained, how a server could index that data, etc)

> New terms should probably be brought up to https://github.com/solid/vocab at some point.

Totally agree - seemed appropriate to first get editorial approval on the text and then propose the terms to vocab, but happy to adjust that approach 😄

**Comment by csarven** [comment]
The connection to DCAT profile is unclear to me... should there be a specific issue about that? The possibility/intention isn't obvious from the first comment - all that's currently asking for is if we can just go ahead and add these terms to solid-terms.

I wanted to understand if/what/how resources including SHACL and ShEx are discovered out there.

Why can't statements pertaining to configuration be (instead) discoverable from describedby's resource? Can you elaborate on the Memento case for instance? Or perhaps: why would the use case require configuration where it wouldn't be possible with describedby?

**Comment by RubenVerborgh** [comment]
If the approval is on the URIs above, then fine.

The title is a tiny bit misleading in the sense that they are relation types (not resource types).

**Comment by csarven** [comment]
Proposal for clients requesting to create Memento's URI-R and have the server create URI-M: https://github.com/solid/specification/issues/61#issuecomment-623386266 . Essentially include header:

```http
PUT https://csarven.ca/linked-research-decentralised-web
Link: <http://mementoweb.org/ns#OriginalResource>; rel="type"
```

URI-M is "server managed".

**Comment by csarven** [comment]
Noting here that the `acl` link relation type is now defined in the Protocol spec. Aside: may eventually go through IANA.

Noting also that http://www.w3.org/ns/auth/acl#accessControl is already defined in the ACL Ontology, and so may be preferable to defining http://www.w3.org/ns/solid/terms#acl

**Comment by csarven** [comment]
Update: acl-link-relation type is defined in the WAC specification: https://solidproject.org/TR/wac#acl-link-relation . Request to register "acl" link relation type is also filed.

To date, no server or application using URIs as alternate relation type to the terms that's currently required and used by the Solid Protocol, i.e., acl, describedby. Closing this issue on that basis but can be reopened if there is demonstrable implementation experience.
