### ISSUE TITLE
Clarify Solid supports a subset of LDP

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/specification#18]
Currently, the spec says `A Solid data pod MUST conform to the LDP specification`.

Would it make sense to clarify that Solid supports only a subset of the LDP spec (specifically, just Basic Containers)?

**Comment by RubenVerborgh** [comment]
Absolutely, that is what needs to be written there. Current sentences are placeholders to get the right normative references in. Hence the TODO Write above 🙂
