### ISSUE TITLE
Document the WAC-Allow header in the spec.

### ISSUE THREAD

**Issue by timbl** [solid/specification#181]
This allows client code to be smart about whether to give the user editing interfaces to data or just view interfaces. 

It also allows them to know whether it open to the public, which might affect for example, whether the user is invited to make a public link, like, bookmark, etc of the resource.

**Comment by csarven** [comment]
Proposal/requirements merged via PR https://github.com/solid/specification/pull/210 . See further details/discussion on concerns of this header, as well as use cases for different permission groups. Implementation feedback is always useful/welcome. Please follow up with new issues/proposals.
