### ISSUE TITLE
Can a non-default ACL apply to a child resource ?

### ISSUE THREAD

**Issue by NSeydoux** [solid/specification#186]
Considering the following interaction:
```
HEAD https://my.pod/container/resource
200
Link: </container/resource.acl>; rel="acl"
---
GET https://my.pod/container/resource.acl
404
--- 
HEAD https://my.pod/container
200
Link: </container/.acl>; rel="acl"
---
GET https://my.pod/container/.acl
200
<#some-rule>
    a acl:Authorization;
    acl:agent <https://my.pod/somewebid#me>;
    acl:accessTo <https://my.pod/container/resource>;
    acl:mode
        acl:Read.
...
```
The ACL document `https://my.pod/container/.acl` contains a resource-scoped ACL rule `#some-rule` that applies to `/container/resource`, while the target resource `https://my.pod/container/resource` does not have an ACL document attached (i.e. the Link with `rel=acl` 404s). 

Is this something that should be allowed by the spec, or does the absence of an ACL document at the place advertised by the resource via the Link header entails that only `acl:default` rules will apply to the resource via its parents ?

If `acl:accessTo` rules are allowed in any ACL document in the hierarchy, one might design a system where only one root ACL document exists, containing `acl:accessTo` rules for any resource in the hierarchy. Could this be consistent with having `acl:Control` access to only a subset of resources ?

**Comment by acoburn** [comment]
In this case, no one would have access to `</container/resource>`. The rules governing this are:

1. Check for an ACL at `</container/resource>` (there is none)
2. Recurse to a parent resource's ACL and stop when one is found (i.e. `</container/.acl>`)
3. Inherit all Authorization rules marked as `acl:default` from that ACL (there are no such rules, therefore no rules grant access, therefore all access is denied).

Please see this explanation by @timbl for this exact issue. Admittedly, the text of the [Web Access Control](https://github.com/solid/web-access-control-spec) spec is confusing on this point.

**Comment by csarven** [comment]
Thanks for this issue and discussion. Closing this issue as consensus is deemed to be captured in WAC Editor's Draft: https://solid.github.io/web-access-control-spec/ . See #effective-acl-resource , #authorization-matching . Please use https://github.com/solid/web-access-control-spec for future discussion.
