### ISSUE TITLE
Strategy for test-suite

### ISSUE THREAD

**Issue by justinwb** [solid/specification#189]
Creating this issue to bring to attention the need for a test suite strategy. Note that there was quite a bit of progress made some months ago by @kjetilk on https://github.com/solid/test-suite, but there hasn't been much activity of late, or use by others working in various areas of the specification and/or implementations. 

Some things to consider:

- Agree whether we're going to adopt the test suite framework at https://github.com/solid/test-suite as is, identity adjustments needed to it to reach adoption, or decide that we want to go in another direction.
- Ensure people working on testable material are aware of how to work with and contribute to the test suite

**Comment by justinwb** [comment]
Noting that there's also a fundamental question about whether to use RDF for writing tests vs. an already established system like jest / supertest, which will need to be evaluated as part of test-suite strategy.

**Comment by kjetilk** [comment]
It seems that what we have arrived at now is that people are free to implement their own test suite, possibly with different scopes and trade-offs, so we're not going for a single one?

**Comment by csarven** [comment]
https://github.com/solid/process/blob/main/test-suite-panel-charter.md addresses this issue as per process and will work out the procedures, e.g., requirements and criteria for publishing test summaries and reports, test suite and test metadata, assessing tests and results.
