### ISSUE TITLE
PUT RDFa, then GET turtle

### ISSUE THREAD

**Issue by michielbdejong** [solid/specification#195]
After storing an RDFa document it should be retrievable as Turtle or JSON-LD.

Two use cases:
* A page like https://csarven.ca/#i to be an html page, but also to act as my WebID for Solid
* A blog post that's a recipe as an html page, but a Solid app can retrieve it as Turtle to put the ingredients on my shopping list.

**Comment by csarven** [comment]
Generally resolved by https://github.com/solid/specification/pull/196 . Re `Accept-Put`: https://github.com/solid/specification/pull/201
