### ISSUE TITLE
iana link relation type uris

### ISSUE THREAD

**Issue by phtyson** [solid/specification#202]
Minor pedantic question. My interpretation of https://www.w3.org/ns/iana/link-relations/relation is that the link relation uris are slash not hash style.
In solid specification draft dated 2020-09-12, example 1 has rel="https://www.w3.org/ns/iana/link-relations/relation#describedby". 
Should that be rel="https://www.w3.org/ns/iana/link-relations/relation/describedby"?

**Comment by csarven** [comment]
# is correct. How did you interpret it to be / ?

**Comment by phtyson** [comment]
Yes of course, on 2nd reading. Been away from RDF and ttl for a while.
