### ISSUE TITLE
README links to https://solid.github.io/specification has been removed

### ISSUE THREAD

**Issue by bourgeoa** [solid/specification#213]
README links to https://solid.github.io/specification has been removed, The link is going to `solid technical reports`

**Comment by csarven** [comment]
Thanks for noting. That's correct. The index.html is now the Solid Technical Reports index. Intended to be like https://www.w3.org/TR/ . The Solid Ecosystem and the Solid Protocol are linked from there. Solid TRs will be made available from https://solidproject.org/TR/ and will change all references made to github.io to the new location.

I'd like to close this issue.. but feel free to comment here or preferably in Gitter chat if you'd like .
