### ISSUE TITLE
keep track of divergences with LDP

### ISSUE THREAD

**Issue by bblfish** [solid/specification#224]
It would be useful to keep track of divergences with LDP, so that we can help understand why those arise, provide feedback to that community, (perhaps even fill in their [errata document](https://www.w3.org/2011/rdf-wg/wiki/Errata)), help implementors and show the way for existing LDP to more easily adopt Solid. 
We could also create a tag "ldp-diff" or something for issues related to this.

This follows from a discussion [on gitter, on Friday 22 Jan 2021](https://gitter.im/solid/specification?at=600abbd1004fab47415a0792).

**Comment by csarven** [comment]
https://github.com/solid/specification/issues/194#issuecomment-694828342
