### ISSUE TITLE
PATCH to create

### ISSUE THREAD

**Issue by michielbdejong** [solid/specification#231]
NSS and PSS support PATCH to create. This means that if do an inserts-only PATCH to a URL that is a 404, that resource is created on the fly. CSS does not support this.

https://github.com/solid/solid-crud-tests/blob/master/test/surface/create-non-container.test.ts#L167 is the test in the test suite for it.

I found the text "[a server creates a resource on HTTP [...] <code>PATCH</code> requests](https://github.com/solid/specification/blob/master/protocol.html#L683)" but I didn't find an explicit statement saying "servers must support PATCH to create".

The old spec said "[If the resource doesn't exist, it should be created through an LDP POST or through a PUT.](https://github.com/solid/solid-spec/blob/master/api-rest.md#alternative-using-sparql-1)" but that's a very old text, predating current NSS behaviour.

I think Solid OS depends on this behaviour, for instance when adding a chat message, if that message happens to be the first message on that day, the document for it gets created on the fly. It's handy. :)

**Comment by bourgeoa** [comment]
Doesn't this MUST imply PATCH create : 
`Servers MUST create intermediate containers and include corresponding containment triples in container representations derived from the URI path component of PUT and PATCH requests`

**Comment by csarven** [comment]
A part of the issue https://github.com/solid/specification/issues/68 included some discussion on PATCH to create a resource. A conclusion was reached in this issue to allow recursive container creation for PATCH. The requirement for this is made it into the spec (after review and approval):

>Servers MUST create intermediate containers and include corresponding containment triples in container representations derived from the URI path component of PUT and PATCH requests. 

Noting here that this requirement is only meaningful for non-existing resources. Also noting that this does not dependent on media type. In practice, I would take that as to apply only to payloads with the intent to 'add' information (at the very least) eg. with application/sparql-update, INSERT DATA would result in the creation of a resource, and DELETE DATA wouldn't.

Another requirement in the spec that also supports PATCH to create based on the review in https://github.com/solid/specification/pull/160#issuecomment-635932724 and approval of:

>Clients who want to assign a URI to a resource, MUST use PUT and PATCH requests.

Aside: the table on PATCH in this comment: https://github.com/solid/specification/issues/14#issuecomment-683480525 has a row for "Write, INSERT DATA, , 200, 201" ie. creating C/R if it doesn't exist.

---

Having said that, there may be other discussions in support of PATCH to create, but equally possible that we've overlooked some conflicting agreements. Also possible that there is a mismatch between what was agreed with what's in the spec. So, I'm all ears.

I'm also interested in knowing why CSS as well as any other server chooses not create a resource with PATCH. Worth bearing in mind that what's currently in the spec (or at least strongly implied) can change if there are good reasons to do so.

**Comment by RubenVerborgh** [comment]
```shell
npm i -g @solid/community-server@0.7.0
community-solid-server &
curl -X PATCH -H 'Content-Type: application/sparql-update' http://localhost:3000/new --data-binary '
  INSERT DATA {
    <https://github.com/solid/specification/issues/231>
        <http://www.w3.org/2000/01/rdf-schema#seeAlso>
            <https://github.com/solid/community-server/pull/597#issuecomment-775351343>.
  }
'
curl http://localhost:3000/new
```

**Comment by acoburn** [comment]
I believe the spec discussions have been really clear on this issue, namely that PATCH can be used to create resources.

I can independently confirm that CSS supports PATCH-to-create.

**Comment by michielbdejong** [comment]
Great!
Thanks for clarifying.

**Comment by michielbdejong** [comment]
Great! I independently confirmed that ESS also supports both PATCH-to-create and PUT-to-create, both including the mkdir-p behaviour.
