### ISSUE TITLE
Header for create container with PUT

### ISSUE THREAD

**Issue by bourgeoa** [solid/specification#232]
@csarven @michielbdejong  This in relation with test-suite

Are body, content-type or link a MUST for create container with PUT ?

And in general are unnecessary specified headers needed in all situations. NSS seems to consider they are not needed when the / semantics on url gives enough information.

**Comment by acoburn** [comment]
https://solidproject.org/TR/protocol#http

> A Solid server MUST reject PUT, POST and PATCH requests without the Content-Type header with a status code of 400.

**Comment by csarven** [comment]
It'd be great if we can keep general Q&As in (Gitter) chat and use repository issues for other stuff.

>Are body, content-type or link a MUST for create container with PUT ?

`Content-Type` is the only requirement (as Aaron quoted). Additional constraints may be applicable.

>And in general are unnecessary specified headers needed in all situations. NSS seems to consider they are not needed when the / semantics on url gives enough information.

I can't quite parse that. Yes, slash semantics apply. Note also which methods should be used for URI allocation. In the case of using POST to create a container (resulting in a server-determined URI, regardless of Slug), 1) request target must be a container with an existing representation, 2) request must include Link header with a valid LDP container type..
