### ISSUE TITLE
Dealing with non-matching DELETE+INSERT sparql-update

### ISSUE THREAD

**Issue by michielbdejong** [solid/specification#234]
There is a "feature" of NSS which Solid OS relies on, which acts as a semaphore when updating a triple somewhere, using sparql-update. For instance if you change your name from Alice to Alicia, with a DELETE+INSERT sparql-update PATCH, but if your current name is not Alice, then the whole request fails. This makes it easier to write Solid apps, because it prevents the risk of ending up with two names if another app just changed your name from Alice to Bob already.

We discussed it at length a few years ago: https://github.com/solid/solid-spec/pull/193/files#diff-a86b670cc11fa633fa242a47094c359f4923ac41702b80b2bf70c05b03d3770aR368-R376

But I don't think that text ever landed in the current spec text, right? Do we still want to add it?

There is also a test for it in the test suite: https://github.com/solid/solid-crud-tests/blob/fc07be5/test/surface/update.test.ts#L276-L328

This test is currently passing for NSS and PSS, but failing for CSS.

**Comment by acoburn** [comment]
HTTP already has a mechanism for avoiding the "lost update" problem: conditional requests via `If-Match` or `If-Unmodified-Since`. I'm not sure why a custom/specialized implementation of SPARQL 1.1 would be desirable for that.

**Comment by RubenVerborgh** [comment]
Duplicate of https://github.com/solid/specification/issues/139

**Comment by michielbdejong** [comment]
Let's discuss there!
