### ISSUE TITLE
OTW: SPS2003 XML Import-Export “Operation” Attribute - 8 content operations

### ISSUE THREAD

**Issue by mwherman2000** [solid/specification#235]
Off The Wall: I've been loosely following the discussion about different operators/verbs/operations for working with resources in a Solid pod.  In my experience with a lot of content migration and content replication platforms, there's actually 8 different _content operations_:

1. operation=”create”
2. operation=”delete”
3. operation=”remove”
4. operation=”replace”
5. operation=”update”
6. operation=”add”
7. operation=”merge”
8. operation=”ignore”

Are all 8 variations accounted for in the Specification?

Reference: [PSN TN0028: SPS2003 XML Import-Export “Operation” Attribute](https://hyperonomy.com/2021/02/12/psn-tn0028-sps2003-xml-import-export-operation-attribute/)

**Comment by csarven** [comment]
re "content operations", the Protocol specification can cover operations on RDF graphs, however not for any data format eg. the Protocol does not specify (or require) how a client can insert 24 frames at t=1978 of a movie object. Servers are free to independently support content operations on any data type.

For strict "content operations" (ie. excluding operations on Web resources), one way is as follows:

Client can use HTTP PATCH (with Content-Type: application/sparql-update) to request RDF graph update operations, ie. to add or remove triple statements, that can be observed in the representation of a resource. The payload of the request follows SPARQL 1.1 Update: https://www.w3.org/TR/sparql11-update/ .

INSERT DATA can be used for "create", "add", "merge", "ignore" operations
DELETE DATA can be used for "delete", "remove", "ignore" operations.
INSERT DATA + DELETE DATA can be used for "replace", "update" operations.

Here "ignore" would entail that the RDF graph didn't change eg. inserting a duplicate statement or there was no matching statement to remove.

Although not yet required but probably will at some point: HTTP POST can be used to merge RDF statements. Servers can optionally support this today.

HTTP PUT could also be used but it is towards creating or replacing Web resources. What constitutes each of the "content operations" there would be processed or interpreted separately by a server. For example, server may reject/ignore a request to change a server-managed statement.

---

If you're generally satisfied with this answer, can we close this issue? If there are use cases that the Protocol must be able support, issues are most welcome.

**Comment by csarven** [comment]
Taking the thumbs up reaction to the comment above as satisfactory. Closing the issue.

**Comment by mwherman2000** [comment]
A thumbs up that the issue was acknowledged in detail.  

@csarven How can/will the 8 operations be added/encoded into the spec?

**Comment by csarven** [comment]
The Solid Protocol most likely will not express each requirement strictly using those 8 operations, although it may use those terms non-normatively as it needs to.

The Solid Protocol for the time being covers/defines the read, write, append operations, and possibly the delete operation soon. Useful enough terms to communicate - not intended to be a 1-1 mapping to all functions. The definitions for the operations are based on existing issues in this repository. The operations are loosely coupled with HTTP verbs (and their affordances) as well as the Web Access Control system. So, the spec is not at all trying to introduce a new "operation" above and beyond what's already well defined and used out there.
