### ISSUE TITLE
Is /foo != /foo/ ?

### ISSUE THREAD

**Issue by bblfish** [solid/specification#240]
In a [discussion on gitter](https://gitter.im/solid/specification?at=60355d3b8031c8234bfe078a) @csarven's wrote:

>  Container and contained resources can be distinguished. If /foo exists, /foo/ can't exist, and vice versa

But the text of [URI Slash Semantics](https://solidproject.org/TR/protocol#uri-slash-semantics) seems to say the opposite

> If two URIs differ only in the trailing slash, and the server has associated a resource with one of them, then the other URI MUST NOT correspond to another resource. 

That seems to say the two resources MUST be the same.

But @RubenVerborgh's [Node Solid Resource Mapping JS](https://github.com/solid/node-solid-server/blob/1afe2f45104a87606007fe97ac443462065cc953/lib/resource-mapper.js#L100) which maps URLs to files seems to me to quite clearly distinguish between URLs ending in a `/` and one's that don't. URLs ending with a `/` are mapped to directories. (I got this from [a discussion on file mappings](https://github.com/solid/specification/issues/237#issuecomment-782817617))
```JS
const isFolder = filePath.endsWith('/')
```
And [on line 115](https://github.com/solid/node-solid-server/blob/1afe2f45104a87606007fe97ac443462065cc953/lib/resource-mapper.js#L115) the content type extension is added to the path that is a request for `/foo` with `text/html` should return `/foo.html` 
```JS
if (!isFolder) {
        path = this._addContentTypeExtension(path, contentType)
 }
```
whereas if the path ends with a `/` then the path is appended with the index file name, i.e., `/foo/` turns into `/foo/index.html` for example.
```
 path += this._indexFilename
 ```
 
 For what it is worth, intuitively the difference makes sense. I think one could even add a Stylistic guidance such as: If both `/foo` and `/foo/` exist, then `/foo` should give an external description of `/foo/` which will give an internal description of the contents, if an RDF request is made. 
 
 That will then leave the question as to whether an RDF file can be an index for a container, as that would then never show the contents, or if the contents should be appended to the container. 
 
 Also the last sentence does not make sense
 >  Behaviour pertaining to authorization MUST proceed this optional redirect
 
 It may do if `proceed` is changed to `precede`

**Comment by TallTed** [comment]
PR #241 will fix the `proceed -> precede` issue you flagged at the end.  As to the preceding...

> In a [discussion on gitter](https://gitter.im/solid/specification?at=60355d3b8031c8234bfe078a) @csarven wrote:
> 
> > Container and contained resources can be distinguished. If /foo exists, /foo/ can't exist, and vice versa
>
> But the text of [URI Slash Semantics](https://solidproject.org/TR/protocol#uri-slash-semantics) seems to say the opposite

You seem to have an unusual definition of "opposite."

> > If two URIs differ only in the trailing slash, and the server has associated a resource with one of them, then the other URI MUST NOT correspond to another resource.
> 

I don't see anything in this that contradicts the earlier.

If `/foo` corresponds to a resource (i.e., exists), then `/foo/` MUST NOT correspond to another resource (which is true if `/foo/` doesn't exist).

> That seems to say the two resources MUST be the same.

It does NOT say that both URIs _MUST_ correspond to _any_ resource (so it does allow for the `404`s @csarven might be suggesting), but it _might_ be read to say that _if_ they both *do* correspond to _any_ resource, _**then**_ both must correspond to the _same_ resource.

I don't see either as forbidding `3xx` redirection from `/foo` to `/foo/` or vice versa.

**Comment by bblfish** [comment]
When I read [Node Resource-mapper](https://github.com/solid/node-solid-server/blob/1afe2f45104a87606007fe97ac443462065cc953/lib/resource-mapper.js#L100) I get the feeling that `/cat` and `/cat/` can be completely different things: the first a `/cat.jpg` and the second an `/cat/index.html` file. Whereas from your interpretation @TallTed the situation seems to be that the first should redirect to the second, which makes them a lot less different. So it just seems that this needs clarification. I am trying to implement this that is why I am providing feedback.

**Comment by RubenVerborgh** [comment]
> In a [discussion on gitter](https://gitter.im/solid/specification?at=60355d3b8031c8234bfe078a) @csarven's wrote:
> 
> > Container and contained resources can be distinguished. If /foo exists, /foo/ can't exist, and vice versa
> 
> But the text of [URI Slash Semantics](https://solidproject.org/TR/protocol#uri-slash-semantics) seems to say the opposite
> 
> > If two URIs differ only in the trailing slash, and the server has associated a resource with one of them, then the other URI MUST NOT correspond to another resource.

Perhaps this is resolved by:

> If /foo exists, /foo/ can't exist as a separate resource

**Comment by RubenVerborgh** [comment]
Perhaps:

> If /foo exists, /foo/ can't exist as a separate resource

**Comment by bblfish** [comment]
@RubenVerborgh wrote:
> If /foo exists, /foo/ can't exist as a separate resource

 but that seems to clash with my reading of your [Node Solid Resource Mapping](https://github.com/solid/node-solid-server/blob/1afe2f45104a87606007fe97ac443462065cc953/lib/resource-mapper.js#L100) I gave above, and also with the answer @csarven gave on gitter.

**Comment by RubenVerborgh** [comment]
> but that seems to clash with my reading of your [Node Solid Resource Mapping](https://github.com/solid/node-solid-server/blob/1afe2f45104a87606007fe97ac443462065cc953/lib/resource-mapper.js#L100) I gave above.

That's ok; it's not authoritative, and that line might or might not have been written by me.

**Comment by bblfish** [comment]
The first part of the sentence does speak about them being distinguished, which was what strengthened my view that they were different.
> Container and contained resources can be distinguished.

Anyway, having them be the same  was closer to how I had already started implement it. Both views can be defended. I wonder if there is a deeper reason for not allowing them to be different.

**Comment by bblfish** [comment]
Ok, I'll close this issue and perhaps open another one seeking justification for the redirect. I'll first look to see if I can find a justification.
