### ISSUE TITLE
Why is defaultForNew deprecated?

### ISSUE THREAD

**Issue by bblfish** [solid/specification#258]
The [acl ontology](http://www.w3.org/ns/auth/acl) has

```Turtlle
 acl:defaultForNew     a rdf:Property;
         :comment """THIS IS OBSOLETE AS OF 2017-08-01.   See 'default'.
        Was: A directory for which this authorization is used for new files in the directory.""";
         :domain acl:Authorization;
         :label "default access for new things in the object" .
```

`defaultForNew` is clearly very useful. It states what acls apply to a newly created resources, and so can be copied over to the new acl of a created resource, and later be edited by the controller. 
`acl:default` applies throughout the life of a resource (as long as the rule holds), so it would always be added back on edit, and hence it may be better to link to it from the new resource, via header perhaps since it can't be changed. 

The proof that it is useful is that [acp wants to bring it back](https://github.com/solid/authorization-panel/blob/initial-acp-spec/proposals/acp/solid-acp.ttl). Here `acp:applyMembers` is the same as `acl:defaultForNew`, since it is distinguished from `applyMembersProtected` in that it can be changed after creation of the new resource.

```Turtle
acp:applyMembers a rdf:Property ;
    rdfs:label "apply members"@en ;
    rdfs:comment "The applyMembers property indentifies the access policies to apply to a resource's members recursively."@en ;
    rdfs:domain acp:AccessControl ;
    rdfs:range acp:Policy ;
    rdfs:isDefinedBy acp: .

acp:applyMembersProtected a rdf:Property ;
    rdfs:label "apply members protected"@en ;
    rdfs:comment """The applyMembersProtected property identifies the access policies to apply to a resource's members recursively.
 These policies may not be removed except by an agent with write access to the ACR where the policy was initially applied."""@en ;
    rdfs:domain acp:AccessControl ;
    rdfs:range acp:Policy ;
    rdfs:isDefinedBy acp: .
```

**Comment by TallTed** [comment]
@bblfish -- You opened it. You can close it...
