### ISSUE TITLE
Create Solid Spec Test Suite

### ISSUE THREAD

**Issue by csarven** [solid/specification#281]
Create Test Suite for implementations to check their conformance to the Solid Spec ( https://github.com/solid/specification/issues/282 )

**Comment by michielbdejong** [comment]
Done! :)
See https://github.com/solid/test-suite and https://gitter.im/solid/test-suite

**Comment by csarven** [comment]
See also https://github.com/solid/specification-tests .

**Comment by csarven** [comment]
Closing this issue as we have multiple test suites (at least for Solid Protocol and WAC) and the work continues in respective repositories.
