### ISSUE TITLE
"acl" should = Active Control List 

### ISSUE THREAD

**Issue by bblfish** [solid/specification#326]
In the [latest WAC spec](https://solid.github.io/web-access-control-spec/) the "acl" link relation points to the resources own ACR even when this does not exist. For Solid servers with simple defaults set at the root that means that most resources would point to ACLs that don't exist. One could imagine a horror situation with a Web Science server hosting billions of documents where each one points to an ACL that does not exist, requiring clients to search for the default making ["2n+1" requests](https://github.com/solid/web-access-control-spec/issues/99). 

Instead the "acl" should point to the active acl (acl = active control list), as that is what authentication libraries have been following to find the access control rules for a resource. A new relation pointing to the Access Control Potential (**ACP**) resource could then be coined.  Perhaps `http://www.w3.org/ns/auth/acp#AccessControl`?  

A server could then return for the `/2021/foo/bar/baz/2093supernovae` resource a 401 with the headers

```http
Link: </default.acl>; rel="acl"
Link: </2021/foo/bar/baz/2093supernovae.acl>; \     
      rel="http://www.w3.org/ns/auth/acp#AccessControl"
```

Possibly the server would not show the ACP link unless the user already has control mode,  as that would be required to create it. Who has control mode could be available from the active ACL. The cost of making a second HTTP request on `/2021/foo/bar/baz/2093supernovae` after having submitted a proof of control mode will not be that problematic. This is in line with the thinking of [issue 325/](https://github.com/solid/specification/issues/325), but now taking the more pragmatic route of having acl point to the effective one.

**Comment by bblfish** [comment]
The nice thing is that for servers where all resources have their own Access Control Resource, as advocated currently by ACP, `acl` and `acp:AccessControl` will coincide.  For servers like existing WAC based ones, where a few default rules exist the two will point to different resources. This will allow the WAC and the ACP systems to come together.

**Comment by bblfish** [comment]
> I don't understand the motivation for this. WAC and ACP address different use cases.

They are both addressing access control use cases. That is all the client at the stage discussed here is wanting to discover: where is the access control resource?

Consider a hyper-App (such as @timbl's Tabulator)  trying to find the access control rules governing a resource on the web. It might have arrived at this resource in any number of ways. So at this point it has no way of knowing if the ontology for describing the rules is WAC or ACP. And that is not yet the question. At this point the client wants to find the rules for access, either to read them and then the "active control list" is the one it is looking for, or to edit it, in which case it may want to create a rule directly for that resource.

**Comment by bblfish** [comment]
I now think it should be the other way. We need a relation to the Active access control container.  See
https://github.com/solid/specification/issues/325#issuecomment-1544244968

**Comment by TallTed** [comment]
So you want to further overload the already [horrendously overloaded `ACL` TLA](https://acronyms.thefreedictionary.com/TLA), differentiating by whether it's uppercase or lowercase? `acl` = `Active [Access] Control List`, while `ACL` = `Access Control List`? This needs a rethink, should it already have been revived or be revived in the future.
