### ISSUE TITLE
Add references for "triple" (and "triple pattern") to the protocol document

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/specification#348]
These terms are currently not defined/referenced.
See https://github.com/solid/specification/pull/346#discussion_r747915497

**Comment by kjetilk** [comment]
Apart from SPARQL, I don't really know which reference that should be... I guess we could be looking back to the early days of semweb data access to see if there is something that predates SPARQL that we could refer to. I think @ericprud is the one who tends to hang around here who were [present at that time](https://lists.w3.org/Archives/Public/public-rdf-dawg/2004AprJun/0385.html). Do you have any suggestions, @ericprud ?

If not, I think we would either refer SPARQL as the normative reference (as I suspect that is actually the earliest spec even though the idea had been around), or we add a simple definition in the preamble of the protocol spec.

**Comment by ericprud** [comment]
I guess [RDF Concepts:triple](https://www.w3.org/TR/rdf11-concepts/#dfn-rdf-triple) and [SPARQL:Triple pattern](https://www.w3.org/TR/sparql11-query/#defn_TriplePattern) are the most foundational you'll find in relatively formalized specs. SPARQL experience came from other languages like [RDQL](https://www.w3.org/Submission/2004/SUBM-RDQL-20040109/) and [Algae](https://www.w3.org/2004/05/06-Algae/) but SPARQL didn't reference them.

**Comment by csarven** [comment]
The Solid Protocol should take care to not (re?)define these terms. Makes sense to reference the specs Eric mentions - and we do refer to RDF 1.1 already in different context. We can include the terms under Terminology with external references.

If we still can't capture this properly in context of N3 Patch, we (Solid CG) should coordinate with the RDF-DEV CG for guidance. It should be defined on a lower level spec as opposed to the Solid Protocol.

**Comment by kjetilk** [comment]
Thanks a lot @ericprud ! Yeah, I agree with @csarven , we shouldn't depart from these existing normative references. So, even though we aren't taking in SPARQL now, I think we would need to use its definition of triple pattern.

**Comment by justinwb** [comment]
> Makes sense to reference the specs Eric mentions - and we do refer to RDF 1.1 already in different context. We can include the terms under Terminology with external references.

Agree with this as well 👍

**Comment by kjetilk** [comment]
There's no assignee, have anybody started writing a PR? If not, I can look at it tonight.

**Comment by kjetilk** [comment]
Fixed in #351.
