### ISSUE TITLE
How should %2F in resource URLs be interpreted?

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/specification#381]
A forward slash `/` can be escaped as `%2F` or `%2f` in a URL.

Given `http://<host>:<port>/<path>?<searchpart>`, should such an escaped slash sequence in the `path` component be treated as:
- a regular slash
- any other character
- a disallowed character
- something else

We should be aware that proxies might perform decoding.

See implementation issues:
- https://github.com/solid/node-solid-server/issues/1666
- https://github.com/solid/community-server/issues/1184

Relates issues:
- https://github.com/solid/specification/issues/22 (special case thereof)

**Comment by ThisIsMissEm** [comment]
This may be relevant: https://simonwillison.net/2022/Mar/5/dash-encoding/

**Comment by kjetilk** [comment]
I see you reference RFC 3986 there in a discussion around URI equivalence, but I think the [relevant section is 2.1](https://datatracker.ietf.org/doc/html/rfc3986#section-2.1):

> A percent-encoding mechanism is used to represent a data octet in a component when that octet's corresponding character [...] is being used as a delimiter of, or within, the component.

In this case, "/" is delimiter, as per the same RFC, and so the percent encoded character is a data octet, that is, "any other character". The URI normalization is also given there.

I'm not sure we should put this in the protocol spec, but we should write a test case for it in a future "relevant tests outside of the protocol spec" test suite to ensure that it does not influence the containment hierarchy in any way. Indeed, `foo/bar` and `foo%2Fbar` are two different resources.

**Comment by kjetilk** [comment]
I created a label to use for things that needs to be revisited for tests, and with that, I think it is OK to close this. Feel free to reopen if you don't agree.
