### ISSUE TITLE
Impact of the storage description resource in v0.9.1

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/specification#449]
CSS implementer feedback:

**In v0.9.0 resources are unaware of the storage that contains them.** The only way to find that storage is for clients to recursively moving up the URI path hierarchy until a container is found with the storage link type header.

**v0.9.1 adds that every storage should have a storage description resource.** The difference with the requirements above is that every resource in a storage needs to return a link header pointing to that description resource. Since that description resource depends on what the storage is, this implies that resources suddenly do need to have some sort of knowledge about the storage they are contained within.

**The impact of this on a server implementation is that for every request targeting a resource, information about all parent resources higher up in the hierarchy will have to be queried to find the matching storage. Or an additional index of some sorts will have to be created internally that keeps track of all the storages.**

---

CSS will implement, but we wanted to share these considerations.

We also note that implementing ACP equally requires servers to traverse to the root, so the same requirement already arises in another place.

**Comment by csarven** [comment]
This is useful and timely implementation feedback, thank you.

Can I ask you to close this comment in favour of re-sharing the comment in issue 355 (or related) which already include lengthy considerations, implementation feedback, and call for implementations/commitments on this topic? (Those and related issues can for the most part remain open until a TR release.) While I understand what you are referring to, the others may not (e.g., no links to existing issues/PRs or links to requirements in specs), and so, it'd be helpful to others to follow along if you can update the comment and refer to specific requirements in specifications.

As mentioned in 355, "storage description of a storage in which this resource is in" feels/works a bit clunky. There is however some anecdotal evidence that applications find it useful to know the storage that a given resource is in - irrespective of the mechanism. As long as discovery of the storage is possible *and* there is a way to either read storage's self-description or the associated description resource via describedby, that may be sufficient for applications. (I'd be in favour of dropping the requirement discovery of the storage description resource https://solidproject.org/ED/protocol#server-storage-description provided that e.g., resource includes pim:storage link relation.)

**Comment by RubenVerborgh** [comment]
Thank you @csarven, moved as a comment.

**Comment by RubenVerborgh** [comment]
Note for posterity: we have numerical evidence at https://testing.solidlab.be/compare/1324/1326, where we see performance halve after adding support.
