### ISSUE TITLE
Required RDF serializations for Solid

### ISSUE THREAD

**Issue by acoburn** [solid/specification#45]
The LDP specification requires read support for both [`text/turtle`](https://www.w3.org/TR/ldp/#h-ldprs-get-turtle) and [`application/ld+json`](https://www.w3.org/TR/ldp/#h-ldprs-get-jsonld). For servers that allow write operations, support for those [two](https://www.w3.org/TR/ldp/#h-ldpc-post-turtle) [formats](https://www.w3.org/TR/ldp/#h-ldpc-post-jsonld) are also required.

Does Solid impose any additional requirements about the support of other RDF serializations for read and/or write operations?

**Comment by csarven** [comment]
If `PUT` becomes a requirement (pending https://github.com/solid/specification/issues/39 , https://github.com/solid/specification/issues/40 ) or at least at the same level as LDP's `POST` ie. optional with some requirements for supporting servers, I'd suggest that the same RDF serializations are supported ie. Turtle, JSON-LD.

Clients intending to create an LDP-RS using a payload in other than Turtle and JSON-LD MUST fulfill https://www.w3.org/TR/ldp/#ldpc-post-createrdf for `POST` as well as `PUT` (pending agreement on support).

Servers supporting Turtle, JSON-LD and optionally other RDF serializations for LDP-RS SHOULD provide different RDF serializations based on client's proactive negotiation. For example, if a server allows the creation of an LDP-RS in `text/html` (including RDFa), it SHOULD respond to `GET` with `Accept: text/turtle` requests with `200`.

**Comment by csarven** [comment]
Noting here that the WebID unofficial draft has MUST for Turtle, allows content-negotiation for other RDF serializations, and has MAY for RDFa. In that regard, the RDFa for WebID raises a slightly stronger recommendation than JSON-LD for WebID. This should also be taken into account in Authentication for both servers and clients.

Also noting here a general status update: the current spec does not require notion of LDP-RS but instead uses the notion of RDF document as in https://www.w3.org/TR/rdf11-concepts/#dfn-rdf-document which includes Turtle, RDFa, JSON-LD, TriG as concrete syntaxes. Will clarify these bits in upcoming PR.

**Comment by csarven** [comment]
Resolved by https://github.com/solid/specification/pull/196
