### ISSUE TITLE
Create serialization format goals and strategy

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/specification#454]
Several specifications within the Solid ecosystem place requirements on the required support for RDF formats.
These requirements typically involve Turtle and JSON-LD, with varying/inconsistent details.

In order to arrive at a consistent strategy regarding serialization formats, I propose to:
1. **Document our goals/intentions**: explicitly write down what we want (and do not want) to achieve with serializations.
2. **Create a cross-spec strategy**: have a shared strategy on which serializations (and with which details) are required.
3. **Align the spec documents**: ensure that the strategy is followed everywhere.

---

In particular, there is some confusion regarding JSON-LD. Some documents will just require that `application/ld+json` is required; others add more specific constraints. Given the absence of a list of goals, we currently cannot check whether those goals are reached by requiring JSON-LD and those specific constraints.

Some specific issues about such constraints are listed in https://github.com/solid/notifications/issues/105.

For the record, I do not have any preferences, not do I propose that this issue becomes a discussion of such preferences.
Rather, this is a work item that needs to be carried out, and specific discussions probably need specific issues.

**Comment by elf-pavlik** [comment]
> Document our goals/intentions: explicitly write down what we want (and do not want) to achieve with serialization.

* For dereferenceable resources (distinct from ephemeral messages that are being passed), one should be able to publish them from a Solid Storage in a reliable way. (Including any storage backed by quad store / SPARQL endpoint)
* Clients should be able to work with just one parser, especially PWA/SPA which needs to keep their bundles low
  * Turtle/Trig parser can be very efficient
  * JSON-LD parser might be easier when the client is also compacting and/or framing internally

**Comment by elf-pavlik** [comment]
> For dereferenceable resources (distinct from ephemeral messages that are being passed), one should be able to publish them from a Solid Storage in a reliable way. (Including any storage backed by quad store / SPARQL endpoint)

To my understanding, Solid Storage *does NOT* guarantee preserving any formatting specific to the serialization used to set the full state of the RDF Source. This includes Turtle comments and prefixes, as well as JSON-LD `@context` and framing.

While some implementations may choose to preserve those details, or it can happen as a simple consequence of using a specific configuration (e.g. filesystem-based persistence). As long as requirements in the spec do not guarantee that, I think we should consider it unreliable.

*NOTE: I don't think spec should guarantee storage to preserve format details for specific RDF serialization, if this needs to be discussed the are separate issues already open*

**Comment by rubensworks** [comment]
> For the record, I do not have any preferences, not do I propose that this issue becomes a discussion of such preferences.
Rather, this is a work item that needs to be carried out, and specific discussion probably need specific issues.

I've created #465 as a place to discuss these preferences.

**Comment by csarven** [comment]
Reopening the issue as it was closed by a non-CG member at the time, without CG's consent. The last useful revision in https://github.com/solid/specification/issues/454#issue-1381227336 is below, before the comment was erased.

---

>Several specifications within the Solid ecosystem place requirements on the required support for RDF formats.
>These requirements typically involve Turtle and JSON-LD, with varying/inconsistent details.

>In order to arrive at a consistent strategy regarding serialization formats, I propose to:
>1. **Document our goals/intentions**: explicitly write down what we want (and do not want) to achieve with serializations.
>2. **Create a cross-spec strategy**: have a shared strategy on which serializations (and with which details) are required.
>3. **Align the spec documents**: ensure that the strategy is followed everywhere.

>---

>In particular, there is some confusion regarding JSON-LD. Some documents will just require that `application/ld+json` is required; others add more specific constraints. Given the absence of a list of goals, we currently cannot check whether those goals are reached by requiring JSON-LD and those specific constraints.

>Some specific issues about such constraints are listed in https://github.com/solid/notifications/issues/105.

>For the record, I do not have any preferences, not do I propose that this issue becomes a discussion of such preferences.
Rather, this is a work item that needs to be carried out, and specific discussion discussions probably need specific issues.

**Comment by RubenVerborgh** [comment]
The above text was written by me, and I do not consent to its usage without prior conversation.
Please remove at your earliest convenience to avoid the need for reporting this copyright violation.

**Comment by csarven** [comment]
GitHub's ToS allow users to reference and reuse publicly available comments within GitHub ([see Section D.5](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#5-license-grant-to-other-users)). And, the [Solid GitHub org](https://github.com/solid/) operates under an MIT license, promoting open collaboration and transparency. So, I see no basis for a copyright violation claim.

**Comment by RubenVerborgh** [comment]
The contributions were not publicly available; copyright claims will be filed.
