### ISSUE TITLE
RDF in text/html

### ISSUE THREAD

**Issue by elf-pavlik** [solid/specification#468]
In #465 I suggested a dedicated issue to deal with nuances of embedding RDF in `text/html`.

I think this issue could result in a CG NOTE which compiles all the relevant information for everyone who wants to work with this feature. 

One of the main topics, in my opinion, will be documenting the pros and cons of using either a `<script>` tag with various RDF formats or RDFa. I think this page on W3C wiki gives a decent start: https://www.w3.org/wiki/N3inHTML

>Contrasted with RDFa
>
>This method differs from RDFa and some other methods for embedding RDF in HTML.
>
> *  It's a multi-graph technique.
> * The RDF is hidden from browsers. (RDFa is usually used to make text that's already human-readable machine-readable too.)
> * Plain old N-Triples can be easily dumped into the HTML without worrying about splitting predicates into prefix:suffix pairs, and without worrying about how to format it to look good for human readers.

I think we should also mention shortly the W3C [Microdata to RDF](https://www.w3.org/TR/microdata-rdf/) TR since [the HTML spec itself defines Microdata](https://html.spec.whatwg.org/#microdata)

**Comment by csarven** [comment]
Not particularly in the scope of the Solid CG but seems suitable for the RDF-DEV CG: https://www.w3.org/groups/cg/rdf-dev
