### ISSUE TITLE
Manual of Style - Spelling

### ISSUE THREAD

**Issue by elf-pavlik** [solid/specification#508]
This issue captures a side conversation started in https://github.com/solid/notifications/pull/162#discussion_r1129023754

> @TallTed Given that we're operating as a [W3C CG](https://www.w3.org/groups/cg/solid/), I think we should be conforming to the [W3C Manual of Style](https://www.w3.org/Guide/manual-of-style/), and to [11.2 Spelling](https://www.w3.org/Guide/manual-of-style/#Spelling) in particular.
> The [W3C Manual of Style](https://www.w3.org/Guide/manual-of-style/) would probably benefit from some attention from the [I18n](https://www.w3.org/groups/wg/i18n-core) folks, and I'd be happy to adjust my editing to such an update.

**Comment by csarven** [comment]
Moved here as it concerns the Solid TR contributing guideline: https://github.com/solid/specification/blob/main/CONTRIBUTING.md (which already refers to W3C Manual of Style).

---

The W3C Manual of Style is a... style preference, nothing more:

>This manual is a guide containing best current practice, written for editors and authors of W3C technical reports. No requirements for W3C publications are in this document. All requirements for W3C publications are in [W3C Publication Rules](https://www.w3.org/pubrules/doc).

And no W3C pubrule requires a particular spelling.

---

The role the Editor of a document is to ensure that the text is easy to read and implement, among other responsibilities. Anyone, including native English speakers, may contribute with improvements, without additional intellectual responsibilities or ownership. In conclusion, it is the Editors' call.

---

Consistency is key. I propose to add the following recommendation under the https://github.com/solid/specification/blob/main/CONTRIBUTING.md#publication-rules

>Use consistent spelling throughout the document.

Proposed in https://github.com/solid/specification/pull/509
