### ISSUE TITLE
WebAC link relation header

### ISSUE THREAD

**Issue by acoburn** [solid/specification#54]
The Solid Web Access Control document describes a [mechanism for ACL resource location discovery](https://github.com/solid/web-access-control-spec#acl-resource-location-discovery). That involves inspecting a Link header with the `rel="acl"` parameter.

That link relation, however, is not registered with [IANA](https://www.iana.org/assignments/link-relations/link-relations.xhtml). Alternatively, many Linked Data specifications ([LDP](https://www.w3.org/TR/ldp/#ldpr-gen-pubclireqs), [LDN](https://www.w3.org/TR/ldn/#discovery), [OA](https://www.w3.org/TR/annotation-protocol/#discovery-of-annotation-containers)) make use of IRIs for use with these sorts of discovery protocols. In the second case, an IRI could be defined in the [ACL vocabulary](http://www.w3.org/ns/auth/acl) without needing to register the relation with IANA.

More discussion of this issue is at https://github.com/solid/web-access-control-spec/issues/21

**Comment by timbl** [comment]
Yes, Let's register this with IANA.    We should definitely not change to use a rel=<URI>, as that would break Solid implementations.

**Comment by csarven** [comment]
Request to register "acl" link relation type: https://github.com/protocol-registries/link-relations/issues/32
