### ISSUE TITLE
Should access grants edit ACLs?

### ISSUE THREAD

**Issue by michielbdejong** [solid/specification#592]
If desired, the ACL system on a Solid storage server (either WAC or ACP), can keep track of all information that is necessary for access decisions. The request made by the client only needs to carry generic identity information (WebID, VC, Client ID, Origin). The ACL document(s) on the storage server act as a guest list.

On the other hand, proposed systems like [SAI](https://solid.github.io/data-interoperability-panel/specification/) and [Inrupt Access Grants](https://docs.inrupt.com/developer-tools/javascript/client-libraries/tutorial/manage-access-requests-grants/) allow moving the access decision away from these on-storage ACL systems and into a separate authorization server.

This authorization server can then either give out a token that contains its decision, or edit the on-storage ACLs to reflect its decision.

IMHO this is a fundamental discussion about how (fine grained) access control works in Solid. Let's have a special topic meeting about it! :)

**Comment by elf-pavlik** [comment]
We had some [discussions around Access Matrix](https://github.com/solid/authorization-panel/discussions/203#discussioncomment-610302)

![matrix](https://user-images.githubusercontent.com/876431/105429915-08b54500-5c18-11eb-81c2-31f9b3a60ec1.png)
![acl](https://user-images.githubusercontent.com/876431/105429932-12d74380-5c18-11eb-851b-eba7dfd7c33c.png)
![cap](https://user-images.githubusercontent.com/876431/105429987-21255f80-5c18-11eb-8b7f-c0b5402f317b.png)

I find it helpful to see that the same Matrix can be collapsed based on resources as well as based on agents. Both ways come useful in different scenarios.
Just as WAC allows use of agent classes in SAI we have somehow comparable way of using resource classes (often based on shapetrees). This way an access policy can be set on the high level which covers:
* resources which don't exist yet, even if they will be created in solid storage yet also not existing at the time
* delegation for resources which haven't been shared yet (possibly also don't even exist yet)

I would also note [ACP Server](https://solid.github.io/authorization-panel/acp-specification/#conforming-acp-server) distinct from [ACP Resource Server](https://solid.github.io/authorization-panel/acp-specification/#conforming-resource-server) which already introduces useful separation.

Last but not least is the delegation, the [most basic documented use case](https://solid.github.io/authorization-panel/authorization-ucr/#uc-client-constraints) I believe is addressed by both SAI and Inrupt Access Grants. We should also make sure that Solid can support longer delegation chains. Based on work with the basic case, dedicated Authorization Server/Agent/Service provides a good place to burden with all the relevant responsibilities.

**Comment by michielbdejong** [comment]
@csarven can you add this to https://github.com/solid/specification/discussions/555 please? Maybe for 2023-11-21?

**Comment by michielbdejong** [comment]
We discussed this and didn't really find a good answer I think. We'll work on this as part of https://github.com/solid/specification/issues/615

**Comment by michielbdejong** [comment]
We discussed this some more in today's UX/DX Improvements meeting.
I'll create a follow-up issue proposing to add SAI as a third option in section 11.
