### ISSUE TITLE
[work item proposal] Solid Application Requirements

### ISSUE THREAD

**Issue by michielbdejong** [solid/specification#615]
[EDITED X2]

This is a [CG work item](https://solidproject.org/TR/#work-items) to produce a new specification which Solid apps should adhere to, with the goal of binding together:
* existing client-client specs such as [Solid Chat](https://solid.github.io/chat/) and [Solid WebID Profile](https://solid.github.io/webid-profile/)
* existing [data convention registries](https://github.com/solid/data-interoperability-panel/discussions/115) such as [ShapeRepo](https://shaperepo.com/), [PDS Interop Conventions](https://github.com/pdsinterop/conventions) and the one that SolidLab Flanders are working one
* existing [app launchers](https://github.com/solid/specification/discussions/603)
* existing access control mechanisms such as [SAI](https://solid.github.io/data-interoperability-panel/specification/), [WAC](https://github.com/solid/web-access-control-spec), [ACP](https://solid.github.io/authorization-panel/acp-specification/), [Distri](https://digita.ai) and [remoteStorage scopes](https://remotestorage.io/protocol/#authorization-oauth-20)

This new spec document will detail the necessary and sufficient requirements an app should adhere to in order for it to be compatible with Solid, hence the name "Solid Application Requirements".

We will have a weekly work meeting, open to all CG participants and under the Solid CG CoCC, every Friday 16:00 CET in https://meet.jit.si/solid-ux-dx-improvements.

**Comment by VirginiaBalseiro** [comment]
Thanks for bringing this up. I agree that focus on improving user and developer experience for Solid is important.

The general understanding is that there are major blocks of initiatives and work in the Solid Project. Specification-centric work is carried out under W3C with the Solid CG and potentially the Solid WG. There are also other significant initiatives that are Solid Project wide. For example, the [Solid Practitioners](https://github.com/solid-contrib/practitioners/) Group is one of those ("bottom-up") undertakings. We also briefly entertained the possibility of a Business Group. And, as you know, the Solid Team stuff.

I think what you're raising highlights a need of the Solid Project as a whole. It might be beneficial to consider Practitioners' Group as a potential venue for this work, or perhaps there is a need to create another group focusing specifically on developing code / libraries. 

@jeff-zucker and I have discussed having more coordination and collaboration between PG and CG. This closer coordination will be highly beneficial to ensure that input and feedback coming from PG makes its way into the specs.

If there is interest in producing documents alongside the code, it would be helpful to clarify the type of document you have in mind. Some documentation efforts might align with the scope of the CG, such as Primers, Use Cases and Requirements; while others could be better suited for different kinds of groups within the Solid Project. For instance, documents aimed at onboarding developers could be developed in the [Getting Started](https://github.com/solid-contrib/getting-started) Group.

**Comment by michielbdejong** [comment]
> When I first suggest Practitioners, I suggested it to be within the CG and was told pretty firmly that outreach and support were not in scope of CG but were in scope of the team.

Right! Those were different times though:
* there was no proposed WG yet
* we still had panels
* we had a full-time spec editor chairing the CG

We have a chance to reconsider now, how we can best manage our project with minimal overhead and maximum progression on its goals.

Looking at the Solid Project with fresh eyes, if the 1.0 spec, its test suite, the panels we used to have, Solid Practitioners, Solid OS, the website, Pivot, SolidCommunity.net, MeIsData.io, Solid Data Modules and Solid Compound all _don't_ fall under the CG then I would like to see a list of activities that *do* happen under the CG, and rough number of FTE working on them.

What comes to mind off the top of my head:
* SAI (~1 FTE?)
* special topic meetings (<.2 FTE?)
* weekly CG call (<.2 FTE?)
* Solid Lite (<1 FTE?)
* anything I forgot?

What we don't want is a CG with more chairs and overhead than actual activity, and then all the interesting Solid Project activities (like Practitioners but also the others I listed) being told they're out of scope. The Solid project has always been about docs + code + specs + tests + practice, not just specs, so we shouldn't define the CG too narrowly.

I'll see if I can find some W3C guidelines about what CGs in general are meant to work on, and what they're meant to leave to their fringes.

**Comment by michielbdejong** [comment]
Right, looking at https://www.w3.org/community/about/#cg and https://www.w3.org/community/about/faq/ it does seem that building actual implementations is quite explicitly out of scope for W3C CGs, the goal should really be to write specs and test suites.

But there is nothing there to say that the writing process should not include experimentation, and that also largely how I see the work item I'm proposing here. It just needs a bit of rewording then.

So not all Solid Data Modules activity can be in scope unless we rebrand the code we write there as just reference / test suite code (which is not such a big step actually).

For Practitioners and Solid OS it might indeed be preferable to say they're not CG activities. I would like to find a way though to make sure that what we spec in the CG matches what is needed in Practitioners and in Solid OS, in terms of implementation feedback and input about stumbling blocks experienced by developers and practitioners. Apart from Jeff's reports about practitioners to the team, I think that's still missing a bit. But let's make that a separate discussion.

**Comment by michielbdejong** [comment]
https://github.com/solid/specification/issues/615#issue-2078622083 updated following your reactions - @VirginiaBalseiro and @jeff-zucker please re-review

**Comment by michielbdejong** [comment]
My main motivation is that currently if we point two developers to https://solidproject.org/TR/ and ask them both to write a Solid app, they will probably write apps that are not interoperable with each other, which sort of defeats the purpose of using Solid in the first place. The proposed UX/DX guidelines spec will hopefully help to fix that.

**Comment by michielbdejong** [comment]
> Those are separate (and important) points. If developers are writing apps that are not interoperable, then it reinforces the point that the proposed specifications for interoperability are not yet adequate. That work is already within the scope, and so I can only encourage us to continue that work further.

Thank you! So the question is, should we distribute that work over the existing work items such as [Solid Application Interoperability](https://solid.github.io/data-interoperability-panel/specification/) and [Solid Chat](https://solid.github.io/chat/) or is there a gap to be filled between them?

**Comment by VirginiaBalseiro** [comment]
Right, some of the UX/DX work you mention could be developed as part of those specifications. My understanding is that this kind of work is or should be taken into account as part of incubation, and generally part of implementation feedback. Other guidelines on these topics could be developed as an extension to Getting Started, and Primers, for example.

**Comment by michielbdejong** [comment]
Thanks also for discussion in Matrix DM. You're right, a CG work item should not have "guidelines" in its title, and a lot of the work from the [Solid Compound milestones](https://github.com/Liquid-Surf/solid-compound/blob/main/docs/milestones.md) would fall under Solid Practitioners and not Solid CG. But there is still quite a bit of work to do in normatively binding together the specs on the client side, so restricting the scope of this work item to just normative spec work, and changing the title to 'Solid Application Requirements'.

**Comment by jeff-zucker** [comment]
>
> Right! Those were different times though:
>
>    - there was no proposed WG yet
>    - we still had panels
>    - we had a full-time spec editor chairing the CG
>
>
You are mistaken.  I proposed this just a month or so ago during the CG
charter discussion at which time none of those things was true.

**Comment by michielbdejong** [comment]
OK I see.
Basically, I'm proposing that
1) "getting Solid working" should be in-scope for the CG. I don't see much point in having a CG if it's just editing specs as loose sand without being guided by that goal.
2) Currently, let's face it, Solid isn't working yet. We don't have interop between https://solidproject.org/apps, we have many different access control mechanism, many different notification channels, we don't have fine-grained access control working, and we don't have app launchers where an end-user can just try out some demo apps and see them working.
3) We (including but not limited to the Solid Data Modules team and the Solid Compound team) are working on fixing this.
4) Given the situation of 2), the work of 3) should be in-scope for 1). Hence this work item proposal to represent it.

Let's discuss in the next CG call! If we can't agree on having this work in-scope for Solid CG then it can still be in-scope for Solid Project / Solid Team of course, but I consider that a plan B.

In the meantime, we will be working on this and having weekly work meetings at 15:00 UTC (16:00 Amsterdam time) each Friday in https://meet.jit.si/solid-ux-dx-improvements

**Comment by michielbdejong** [comment]
After some more thought and useful conversation with @VirginiaBalseiro and others, I'll first propose a Solid Team task force about this work, to give it a place, and then if we're ready to be writing specs we can always still morph it into a CG work item at that time.

**Comment by michielbdejong** [comment]
See https://matrix.to/#/!ogHmAuzhszmxlGQrVp:gitter.im/$iQ-NfYJW7zbReu4glJymRm2puVp8KuwVgWBfXm19EBE?via=gitter.im&via=matrix.org&via=attendees.fosdem.org and https://github.com/solid/team/pull/54

**Comment by csarven** [comment]
@michielbdejong , @VirginiaBalseiro , you beat me to responding in this thread :) but I've been thinking and PR'd a simple guide about Workspace Selection inspired by this issue and discussion elsewhere (e.g., CG charter with Jeff): https://github.com/w3c-cg/solid/pull/16 . I think that can help us quickly address common scenarios and keep some perspective/focus.

Just want to also acknowledge that what's brought up in this issue is important and useful. IMO, the work goes beyond the CG, and would even include the WG, and in various ways Practitioners, and as Michiel (just said as I'm writing this) DX/UX work in general in the community.
