### ISSUE TITLE
Container creation via PUT

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/specification#62]
(Related to [#40-Can a client create Solid resources via PUT](https://github.com/solid/specification/issues/40))
Proposal: Solid spec should support the creation of Containers via PUT (currently, only POST is supported).

**Comment by csarven** [comment]
Wouldn't this feature be covered under https://github.com/solid/specification/issues/40 given any LDP Resource? Perhaps we cover this there so the discussion around PUT is kept together and we don't miss anything?

In any case, I would say, yes PUT for Container should be possible, provided that it follows the same containment rules as everything else.

**Comment by dmitrizagidulin** [comment]
@csarven Ah, yes, ok, I wasn't sure if #40 was targeting _non-container_ resources. I'm happy to close this as a duplicate.
