### ISSUE TITLE
Determine the fate of the Globbing mechanism

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/specification#64]
Currently, the much-contentious Globbing mechanism is marked 'at risk' on the existing spec.
As part of the 1.0 spec we should decide its fate (either continue marking it at at-risk, or, preferably, decide one way or another).

Related issues:

* https://github.com/solid/solid-spec/issues/145
* https://github.com/solid/solid-spec/pull/148
* https://github.com/solid/solid-spec/pull/151
* https://github.com/solid/solid-spec/issues/149
* https://github.com/solid/solid-spec/issues/147
* https://github.com/solid/solid/issues/115

**Comment by RubenVerborgh** [comment]
1.0 should either include or exclude features; not have any at risk.

As for globbing, I strongly feel we should exclude it for reasons mentioned in the above threads, which also link to a 10-line client-side alternative I wrote.

**Comment by dmitrizagidulin** [comment]
My vote is: +1 to what @RubenVerborgh said.

**Comment by justinwb** [comment]
Agree on exclusion. IMO - this has lingered for a long time when there are legitimate alternatives and it’s a good time to move from at risk to excluded in the next major version.

**Comment by RubenVerborgh** [comment]
Then I hereby decide to _not_ include globbing, unless any objections come up. (Since there is no text to be reviewed for _not_ adding a feature, there is nothing more we can do process-wise.)

**Comment by kjetilk** [comment]
Moved to "Done". IIRC; it is possible to automated that in the project board.
