### ISSUE TITLE
Work item proposal: client-client protocol(s) for farm management or ERP

### ISSUE THREAD

**Issue by lecoqlibre** [solid/specification#694]
Like I announced it several times in CG meetings I would like to propose a new work item to work on farm management client-client protocol(s) (c2c). Having such protocol(s) would make possible the development of interoperable agriculture applications within the Solid ecosystem.

Farm management is very wide and includes the ability to manage orders, invoices, crops, products, catalogs, accounting, clients, etc. The farmers I'm working with asked me to first develop an app to compose the baskets/boxes of products they deliver generally each week as they are engaged into a Community-supported agriculture (CSA model) system. This app needs to allow them to manage their products and distributions (which can be seen as orders).

It appears that farm management shares a lot of concepts with ERPs. One big difficulty here is to scope the features into a consistent c2c protocol or set of c2c protocols. So one idea would be to first work on a c2c protocol that would rule general ERP systems? Farm management apps would also follow this protocol.

With that "Solid ERP" c2c protocol idea in mind I started to work on something some months ago. All the data would be kept into the container of the company/enterprise. This container would contain orders, catalogs, products and so on. The enterprise container would be registered into the public or private TypeIndex of the profile they are linked to. When starting, apps would ask users to select the enterprise they want to work with (users can manage multiple enterprises).

In term of vocabularies I worked with the one from the [Data Food Consortium](https://github.com/datafoodconsortium/ontology) project. Other vocabularies exist like the one from [GS1](https://ref.gs1.org/voc/) and also the [smartdatamodels (Fiware)](https://github.com/smart-data-models/data-models) project. Also [FarmConvention](https://our-sci.gitlab.io/conventions/common_farm_conventions/wiki/docs/Conventions/log/log--activity--flaming/) is an interesting non-RDF project. Do you know some others?

What do you think? Do you have any input, advise or guideline you would like to share on the subject?

**Comment by michielbdejong** [comment]
Awesome!
There were no objections in today's CG call to the creation of this work item.
@elf-pavlik and myself will co-champion this.
We agreed on the name 'ERP' for this client-to-client protocol, similar to the existing 'Chat' one.
I asked @jeswr to create a repo https://github.com/solid/erp for it.

**Comment by jeswr** [comment]
Is there a particular template you want for this @michielbdejong @lecoqlibre e.g. default respec?

**Comment by lecoqlibre** [comment]
Hi @jeswr, we talked about to use Bikeshed preferably.

**Comment by jeswr** [comment]
Ok, repo created. @michielbdejong and @lecoqlibre you have been given write access.

**Comment by gbathree** [comment]
We also have a bi-weekly meeting you can join - https://calendar.app.google/BoM66gcXG1HQ8w8R8.
