### ISSUE TITLE
Establish versioned or living standard model for specs

### ISSUE THREAD

**Issue by csarven** [solid/specification#8]
All specifications should be up front up about what to expect ie. are specs versioned or following a living standard model.

To avoid complications down the line and to learn from what's nearby, I'd like to point to https://www.w3.org/2019/04/WHATWG-W3C-MOU.html

Discuss.

**Comment by RubenVerborgh** [comment]
Versioned. And we have different documents that can be in different versions.

**Comment by csarven** [comment]
Was that a unanimous/collective decision? Public discussion somewhere that I missed? Whatever is the decision, it has ramifications and I'd like make sure that's acknowledged and adhered down the line.

There are (dis)advantages to both.. versioned would entail that an implementation may conform to version X but not Y... so "interop" in context of versoin.  Living Standard may entail or expected that implementations need to keep up with the spec and may not need to signal which features they support... or LS needs to be always backwards compatible or not.. There are finer details here that we should be careful about.

**Comment by RubenVerborgh** [comment]
> Was that a unanimous/collective decision?

My opinion, since this post said "Discuss" 🙂 Clarified.

**Comment by justinwb** [comment]
My opinion: it would be ideal to have version tracking, but also have an expectation that implementations keep up with the specification. Any change that impacts backwards compatibility after a specification reaches its first major version (1.0) should be taken extremely seriously and need to have an extremely strong case behind it.

**Comment by kjetilk** [comment]
Actually, I think that it would be reasonable to develop living standards as long as we (for some value of "we") are at the helm, but that we should have the ambition to graduate the development of the specifications into the W3C process with the formation of the WG, in which case it would stop being a living standard. We would probably still be deeply involved, but it would follow a different process, some of which might result in Recommendations, some may result in Notes. Exactly at what point a WG becomes appropriate, I'm not sure, but also not just up to us to decide, but I think we should have that in mind.

So, with some opinions stated, we should have a discussion :-)

**Comment by kjetilk** [comment]
> https://www.w3.org/wiki/Evergreen_Standards has good documentation / considerations / expectations / practices.. on living standards.

Ah, I hadn't seen that. Thanks, @csarven ! @Mitzi-Laszlo , have you seen that? I think it is worth having a look at.

**Comment by kjetilk** [comment]
Consensus from Editor’s Meeting 2021-06-01 with @timbl @justinwb, @csarven and @kjetilk present:

The Editors prefer a versioned specification approach to allow implementers to code against a stable version.
