### ISSUE TITLE
mkdir-p only for PUT or also for POST?

### ISSUE THREAD

**Issue by michielbdejong** [solid/specification#93]
```sh
$ curl -X PUT https://michielbdejong.solid.community/public/public-write/asdf-put -d "b la"
Created
$ curl -X POST https://michielbdejong.solid.community/public/public-write/asdf-post/ -d "bla"
Container not valid
```

So looks like NSS only does mkdir-p for PUT, not for POST. Is that how the spec intends it?

This is a question that came up at [Solid Amsterdam](https://www.meetup.com/Solid-Netherlands/events/263745707/) yesterday.

It does seem so now that I read [the text about it](https://github.com/solid/solid-spec/blob/master/api-rest.md#http-put-to-create)?

**Comment by csarven** [comment]
Is this a duplicate of https://github.com/solid/specification/issues/68 or https://github.com/solid/specification/issues/40 ? mkdir is mentioned. Would it make sense to raise this in those issues?

**Comment by michielbdejong** [comment]
Ah yes sorry! #68 already covers this.
