### ISSUE TITLE
Does the 1.0 spec still require a File System representation?

### ISSUE THREAD

**Issue by humont** [solid/specification#94]
This was a basic premise in the original NSS, as well as in the spec v.0.7.0.

Is this still being considered as a requirement for future development - I do not see a section header for it in the current draft document.

**Comment by RubenVerborgh** [comment]
What do you mean with “file system representation”?

Solid only governs the interfaces, not the storage (although we might spec that at some point), There were never any file system requirements.

**Comment by humont** [comment]
See [this link](https://github.com/solid/solid-spec/blob/master/content-representation.md#objects) for reference. My understanding was that there was a mapping between URL-space and file-space.

> A very important aspect of Solid revolves around naming resources, and keep the namespaces consistent across both the Web and local file systems.

For example, the NSS uses the file system as a persistence layer, and reads it out into a graph before sending by HTTP (in the case of RDF resources).

Wondering if this will be the case going forward, or whether storing everything in a LDP graph for persistence will be acceptable?

**Comment by RubenVerborgh** [comment]
My understanding is that, _if_ the backend is a filesystem, then it _should_ follow some to-be-detailed format in order to be portable. A suggested mapping is in https://www.w3.org/DesignIssues/HTTPFilenameMapping.html.

**Comment by humont** [comment]
Thanks for the clarification - i wasn't sure if the precedent being set by NSS would be normalised into the spec.

Though there is something quite wonderful about the concept of simply being able to drag a folder around from a data-portability perspective!
