### ISSUE TITLE
Stronger requirements on payload fields?

### ISSUE THREAD

**Issue by kjetilk** [solid/specification#95]
@michielbdejong brought up the payload header fields for `HEAD` requests in https://github.com/solid/test-suite/issues/24 , i.e. headers that may be omitted for `HEAD`.

My hunch is that we should be stronger, especially `Content-Length` would intuitively be very important for decentralized applications to discover, it may be that the sole reason for `HEAD` is to get it. OTOH, it may be that the response is generated on the fly, so it is not known with any accuracy before actual representation is generated. Not sure, but I would tend to a stronger requirement on some of these, perhaps even MUST.

**Comment by RubenVerborgh** [comment]
I am fine with HTTP:

> The server SHOULD send the same
   header fields in response to a HEAD request as it would have sent if
   the request had been a GET, except that the payload header fields
   (Section 3.3) MAY be omitted.

—https://tools.ietf.org/html/rfc7231#section-4.3.2

That's a SHOULD and a MAY, so no strong suggestion to omit those headers.

It could become expensive for servers to always have to generate response lengths; I would leave it up to them to decide when they can do so easily.

In general, I also think we should not add too many additional constraints on top of the specs we implement, because there's already quite some of them, and it limits the extent to which other libraries for those specs can be reused as-is.

**Comment by kjetilk** [comment]
It goes out on a tangent, but it relates to my general opinion on why the Web tended towards centralization. It was obviously all the legal and economic issues, but it was also technical, since decentralization is harder. Arguably, there is a lot in the specs that would have aided decentralization, caching, conditional requests, and an easy to get to content length are amongst them. However, as these things tended to be deprioritized in product roadmaps as nice-to-haves. My main concern is that we don't fall into that trap again. 

Now, there are several ways to avoid that trap, and stronger specs are not necessarily the most important. Arguably, the most important is tool support that enables developers to do all the MAYs and SHOULDs Done Right with ease, but it may be that the spec should enforce it. 

As a general rule, I agree with that we should have evidence to add a MUST, but then we have to commit resources to study it, and I am afraid that once that evidence surfaces, it may be too late.

**Comment by elf-pavlik** [comment]
> It could become expensive for servers to always have to generate response lengths;

I think response length could get calculated just on writes and then reused on all following reads.

@kjetilk could you document use case backing your statement

> especially Content-Length would intuitively be very important for decentralized applications to discover, it may be that the sole reason for HEAD is to get it.

**Comment by csarven** [comment]
>I think response length could get calculated just on writes and then reused on all following reads.

Possible but isn't that only really useful per representation? Unless the requirement is to calculate up front for all supported serializations and possible representations. Also need to factor in how it should be stored and recalled from - although the `.meta` approach is probably the main candidate this is still an open issue - as well as updating the value when the representation data gets updated. For cached or Memento resources, write-once-read-many may be most useful but it seems a bit complex to set it up front? Not dismissing the idea, just contrasting.

**Comment by kjetilk** [comment]
Right, so my main use case is as a proxy for resource size for use in a query planner in cases where the triple count estimator of TPF is too expensive to compute. 

But then, as I suppose you allude to, @csarven , this use doesn't require an exact number, so it might be better done by an entirely different system to compute a more suitable heuristic, and thus also expose it in a separate way.

**Comment by RubenVerborgh** [comment]
> for use in a query planner in cases where the triple count estimator of TPF is too expensive to compute.

But those are query-specific interfaces then, for which we might have different requirements anyway.

(Also, note that TPF estimates serve to count the number of matches across pages; the size of a single representation is not a proxy for that.)

**Comment by kjetilk** [comment]
> > for use in a query planner in cases where the triple count estimator of TPF is too expensive to compute.
> 
> But those are query-specific interfaces then, for which we might have different requirements anyway.

Yes, but there is some attraction in re-using commonly available data.

> (Also, note that TPF estimates serve to count the number of matches across pages; the size of a single representation is not a proxy for that.)

No, but in a LD traversal query interface, the size of the representation could a proxy for the size of the data contained in that representation. It all depends on how we end up querying.

**Comment by RubenVerborgh** [comment]
For all query purposes, there's no harm in doing a `GET` and closing the connection when you don't want it after all. Doing the `HEAD` only creates overhead if you will request the resource anyway.

I don't mean to go deep into querying, but rather want to arrive at a clear case when, yes, a MUST on payload header fields with `HEAD` will make a crucial difference.

**Comment by kjetilk** [comment]
> For all query purposes, there's no harm in doing a `GET` and closing the connection when you don't want it after all. Doing the `HEAD` only creates overhead if you will request the resource anyway.

I'm thinking that e.g. an IDP planner is exploring the available space, and is doing `HEAD` requests to prune possible plans based on it. In that case, it may not request a representation, it may only request metadata to determine that it will prune the plan where it would be.

> I don't mean to go deep into querying, but rather want to arrive at a clear case when, yes, a MUST on payload header fields with `HEAD` will make a crucial difference.

Fine, in that case, we actually need to write the planner to see. 

I'll close this issue for now, then, but I hope we can write that planner at some point. :-)
